plugins:
  - jekyll-spaceship

theme: jekyll-theme-architect

title: hahadsg's note
description: ''

highlighter: rouge

repository: hahadsg/hahadsg.github.io

jekyll-spaceship:
  # default enabled processors
  processors:
    - mermaid-processor
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
